export default function ProjectStructure() {
  return (
    <section id="project-structure">
      <h1>Project structure</h1>
      <p>
        This project use similar architecture from many frameworks such as
        Laravel or Adonis.js but with less complex and more flexible to modify.
      </p>
      <pre>{`MyApp/
├── node_modules
├── public
├── src/
│   ├── Configs
│   ├── Controllers
│   ├── Middlewares
│   ├── Models
│   ├── Resources/
│   │   ├── assets
│   │   ├── css
│   │   └── ts/
│   │       ├── components
│   │       └── Pages
│   └── Views
├── storage
└── vendor`}</pre>
      <ul>
        <li>
          <b>node_modules</b> The Node.js module folder (generated by npm).
        </li>
        <li>
          <b>public</b> For static files and main entry of the app.
        </li>
        <li>
          <b>src</b> Main source code folder.
          <ul>
            <li>
              <b>Configs</b> Config files such as database.
            </li>
            <li>
              <b>Controllers</b> Controller files.
            </li>
            <li>
              <b>Middlewares</b> Middlware files.
            </li>
            <li>
              <b>Models</b> Model files.
            </li>
            <li>
              <b>Resources</b> For client-side script and assets.
              <ul>
                <li>
                  <b>assets</b> For assets (Images, audio, JSON, etc.).
                </li>
                <li>
                  <b>css</b> For stylesheets.
                </li>
                <li>
                  <b>ts</b> For Typescript code.
                  <ul>
                    <li>
                      <b>components</b> For re-usable components.
                    </li>
                    <li>
                      <b>Pages</b> For page components.
                    </li>
                  </ul>
                </li>
              </ul>
            </li>
            <li>
              <b>Views</b> For PHP view renderer.
            </li>
            <li>
              <b>storage</b> For application's storage.
            </li>
            <li>
              <b>vendor</b> PHP packages folder
            </li>
          </ul>
        </li>
      </ul>
    </section>
  );
}
