import hljs from "highlight.js";
import "highlight.js/styles/nord.css";
import Controller from "../components/docs/Controller";
import Middleware from "../components/docs/Middleware";
import Model from "../components/docs/Model";
import ReactDoc from "../components/docs/ReactDoc";

export default function Docs() {
  return (
    <>
      <nav className="fixed bottom-0 top-0 left-0 bg-white h-screen border-r p-4 pt-16">
        <div className="prose prose-sm prose-a:no-underline prose-ul:list-none prose-ul:p-0">
          <h3>Documentation</h3>
          <ul className="prose-li:pl-0">
            <li>
              <a href="#get-start" className="font-bold">
                Get start
              </a>
              <ul>
                <li>
                  <a href="#installation">Installation</a>
                </li>
                <li>
                  <a href="#project-structure">Project structure</a>
                </li>
              </ul>
            </li>
            <li>
              <a href="#api-reference" className="font-bold">
                API Reference
              </a>
              <ul>
                <li>
                  <a href="#controller">Controller</a>
                </li>
                <li>
                  <a href="#middleware">Middleware</a>
                </li>
                <li>
                  <a href="#model">Model</a>
                </li>
                <li>
                  <a href="#router">React</a>
                </li>
                <li>
                  <a href="#router">Router</a>
                </li>
                <li>
                  <a href="#storage">Storage</a>
                </li>
              </ul>
            </li>
          </ul>
        </div>
      </nav>
      <div className="prose max-w-6xl py-10 ml-96">
        <section id="get-start">
          <h1>Get start</h1>
          <section id="installation">
            <h2>Installation</h2>
            <ul>
              <li>
                <a href="https://www.git-scm.com/">Git</a>
              </li>
              <li>
                <a href="https://www.php.net/">PHP</a>
              </li>
              <li>
                <a href="https://getcomposer.org/">Composer</a>
              </li>
              <li>
                <a href="https://nodejs.org/en">Node.js & NPM</a>
              </li>
            </ul>
            <h3>Setup project</h3>
            <ol>
              <li>
                <p>Clone project to your computer</p>
                <pre>
                  <code>
                    git clone https://github.com/pwnrrk/php-mvc.git
                    /path/to/yourproject/
                  </code>
                </pre>
              </li>
              <li>
                <p>Change git origin to your account</p>
                <pre>
                  <code>
                    git remote set-url origin https://github.com/user/repo2.git
                  </code>
                </pre>
              </li>
              <li>
                <p>Install PHP and Node.js packages</p>
                <pre>
                  <code>
                    # Install PHP packages <br />
                    composer install <br />
                    <br />
                    # Install Node.js packages <br />
                    npm install
                  </code>
                </pre>
              </li>
            </ol>
            <h3>Runing development server</h3>
            <ol>
              <li>
                <p>PHP development server</p>
                <pre>
                  <code>php -S 0.0.0.0:8000 -t public</code>
                </pre>
              </li>
              <li>
                <p>Webpack watch</p>
                <pre>
                  <code>npm run watch</code>
                </pre>
                See more script in package.json
              </li>
              <li>
                <p>
                  Go to{" "}
                  <a href="http://localhost:8000">http://localhost:8000</a>
                </p>
              </li>
            </ol>
          </section>
          <section id="project-structure">
            <h2>Project structure</h2>
            <p>
              This project use similar architechture from many frameworks such
              as Laravel or Adonis.js but with less complex and more flexible to
              modify.
            </p>
            <pre>{`MyApp/
├── node_modules
├── public
├── src/
│   ├── Configs
│   ├── Controllers
│   ├── Middlewares
│   ├── Models
│   ├── Resources/
│   │   ├── assets
│   │   ├── css
│   │   └── ts/
│   │       ├── components
│   │       └── Pages
│   └── Views
├── storage
└── vendor`}</pre>
            <ul>
              <li>
                <b>node_modules</b> The Node.js module folder (generated by
                npm).
              </li>
              <li>
                <b>public</b> For static files and main entry of the app.
              </li>
              <li>
                <b>src</b> Main source code folder.
                <ul>
                  <li>
                    <b>Configs</b> Config files such as database.
                  </li>
                  <li>
                    <b>Controllers</b> Controller files.
                  </li>
                  <li>
                    <b>Middlewares</b> Middlware files.
                  </li>
                  <li>
                    <b>Models</b> Model files.
                  </li>
                  <li>
                    <b>Resources</b> For client-side script and assets.
                    <ul>
                      <li>
                        <b>assets</b> For assets (Images, audio, JSON, etc.).
                      </li>
                      <li>
                        <b>css</b> For stylesheets.
                      </li>
                      <li>
                        <b>ts</b> For Typescript code.
                        <ul>
                          <li>
                            <b>components</b> For re-usable components.
                          </li>
                          <li>
                            <b>Pages</b> For page components.
                          </li>
                        </ul>
                      </li>
                    </ul>
                  </li>
                  <li>
                    <b>Views</b> For PHP view renderer.
                  </li>
                  <li>
                    <b>storage</b> For application's storage.
                  </li>
                  <li>
                    <b>vendor</b> PHP packages folder
                  </li>
                </ul>
              </li>
            </ul>
          </section>
        </section>
        <hr />
        <section id="api-reference">
          <Controller />
          <hr />
          <Middleware />
          <hr />
          <Model />
          <hr />
          <ReactDoc />
          <hr />
        </section>
      </div>
    </>
  );
}
